[package]
name = "rucash"
version = "0.1.2"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/z-Wind/rucash"
description = "read Gnucash sql file"
keywords = ["gnucash"]
categories = ["database"]
authors = ["zWindr <zpsyhapcst@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.5", features = [ "runtime-async-std-native-tls", "sqlite", "postgres", "mysql", "chrono", "decimal" ] }
futures = "0.3"
chrono = "0.4"
rust_decimal = "1.13"
rust_decimal_macros = "1.13"
criterion = "0.3"
xmltree = "0.10"
either = "1.6"
itertools = "0.10"

[lib]
name = "rucash"
crate-type = ["cdylib", "rlib"]

[[bench]]
name = "benchmark"
harness = false
