[package]
name = "rucash"
version = "0.1.7"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/z-Wind/rucash"
description = "read Gnucash sql file"
keywords = ["gnucash"]
categories = ["database"]
authors = ["zWindr <zpsyhapcst@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.5", optional = true }
futures = "0.3"
chrono = "0.4"
rust_decimal = "1.13"
#rust_decimal_macros = "1.13"
xmltree =  { version = "0.10", optional = true }
itertools = "0.10"
flate2 = "1.0"

[lib]
name = "rucash"
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false
required-features = ["sqlite"]

[features]
default = []
sqlx_common = [ "sqlx/runtime-async-std-native-tls", "sqlx/macros", "sqlx/chrono", "sqlx/decimal" ]
sqlite = [ "sqlx_common", "sqlx/sqlite" ]
postgres = [ "sqlx_common", "sqlx/postgres" ]
mysql = [ "sqlx_common", "sqlx/mysql" ]
xml = [ "xmltree"]

[[test]]
name = "sqlite"
path = "tests/sqlite.rs"
required-features = ["sqlite"]

[[test]]
name = "postgresql"
path = "tests/postgresql.rs"
required-features = ["postgres"]

[[test]]
name = "mysql"
path = "tests/mysql.rs"
required-features = ["mysql"]

[[test]]
name = "xml"
path = "tests/xml.rs"
required-features = ["xml"]

[[test]]
name = "all"
path = "tests/all.rs"
required-features = ["sqlite", "postgres", "mysql", "xml"]